name: Build Ubuntu Standalone

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build standalone binary
        run: |
          go build -o rclone_password_reveal

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rclone_password_reveal
          path: rclone_password_reveal
